language: python

python:
  - 2.7
  - pypy

env:
  # Test against the minimum supported version of eliot
  - |
    ELIOT='echo -n "eliot=="; python -c "from setup import _MINIMUM_ELIOT_VERSION; print _MINIMUM_ELIOT_VERSION"'

  # Test against the released version of eliot which pip will choose to
  # install.
  - |
    ELIOT='echo eliot'

  # Test against master@HEAD version of eliot.
  - |
    ELIOT='echo git+https://github.com/hybridcluster/eliot.git'

  # Test with a too-old version of eliot.
  - |
    ELIOT='echo eliot==0.3.0'

  # Test without any version of eliot.
  - |
    NO_ELIOT=''

install:
  - |
    pip install coveralls coverage

  - |
    python setup.py --version

  # Install the selected eliot version.
  - |
    if [ -v ELIOT ]; then
        pip install "$(eval ${ELIOT})"
    fi

  - |
    pip install -e .

script:
  - |
    coverage run --branch --source machinist $(type -p trial) machinist
  - |
    coverage report -m

after_success:
  - |
    coveralls

notifications:
  email: false
